### ISSUE TITLE
Cross compile and provide binaries for Linux and Windows

### ISSUE THREAD

**Issue by talkol** [orbs-network/orbs-key-generator#2]
This tool is (potentially - verify the latest validator instructions) used to create a node.

Not all validators have Macs, so we should provide binaries for all popular operating systems.

Cross compiling is a little difficult because we have a dependency on [secp256k1-go](https://github.com/orbs-network/secp256k1-go/tree/master/libsecp256k1/src) which is a C codebase

This means we need to compile with CGO (it's no longer a pure go project) - which makes cross-compilation more difficult. See this tutorial for example:

https://dh1tw.de/2019/12/cross-compiling-golang-cgo-projects/

We get the failures currently when running: `./build-binaries.sh` - that's the script that does the cross compilation for Mac, Linux and Windows (inspiration taken from gamma-cli which is a pure go project that's easy to cross-compile)

**Comment by netoneko** [comment]
Fixed by moving to JS.
